POST http://localhost:3000/api/station/create
Content-Type: application/json

[
  {"estacionId":1,"nombre":"Estación Central Norte","direccion":"Av. Libertador 1250","tipoParada":"Inicio","estadoEstacion":1},
  {"estacionId":2,"nombre":"Plaza San Martín","direccion":"Plaza San Martín s/n","tipoParada":"Inicio","estadoEstacion":1},
  {"estacionId":3,"nombre":"Terminal Belgrano","direccion":"Av. Belgrano 3400","tipoParada":"Inicio","estadoEstacion":1},
  
  {"estacionId":4,"nombre":"Barrio Norte","direccion":"Av. Santa Fe 2100","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":5,"nombre":"Palermo Chico","direccion":"Av. del Libertador 1800","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":6,"nombre":"Recoleta","direccion":"Av. Pueyrredón 1900","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":7,"nombre":"Retiro","direccion":"Plaza San Martín 300","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":8,"nombre":"Puerto Madero","direccion":"Av. Alicia Moreau de Justo 1150","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":9,"nombre":"San Telmo","direccion":"Defensa 800","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":10,"nombre":"La Boca","direccion":"Av. Pedro de Mendoza 1835","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":11,"nombre":"Barracas","direccion":"Av. Montes de Oca 1200","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":12,"nombre":"Constitución","direccion":"Plaza Constitución s/n","tipoParada":"Intermedia","estadoEstacion":1},
  {"estacionId":13,"nombre":"San Cristóbal","direccion":"Av. Entre Ríos 1400","tipoParada":"Intermedia","estadoEstacion":1},

  {"estacionId":14,"nombre":"Terminal Sur","direccion":"Av. 9 de Julio 3500","tipoParada":"Final","estadoEstacion":1},
  {"estacionId":15,"nombre":"Estación Riachuelo","direccion":"Av. Riachuelo 2200","tipoParada":"Final","estadoEstacion":1},
  {"estacionId":16,"nombre":"Terminal Oeste","direccion":"Av. Rivadavia 8500","tipoParada":"Final","estadoEstacion":1}
]

##########
GET http://localhost:3000/api/station/all 

#####


POST http://localhost:3000/api/routeStation/create
Content-Type: application/json

{
  "inicio":1,
  "intermedio":[4,5,6,7,8,9],
  "final":14,
  "horaInicio":"12:00",
  "horaFin":"22:00"
}

####
GET http://localhost:3000/api/routeStation/all
###

PUT http://localhost:3000/api/routeStation/delete
Content-Type: application/json

{
  "routeId":0
}

###
GET http://localhost:3000/api/routeStation/unic
Content-Type: application/json

{
  "routeId":0
}


###
PUT http://localhost:3000/api/routeStation/update
Content-Type: application/json

{
  "routeId":0,
  "final":14,
  "horaInicio":"12:00asfasf",
  "horaFin":"24:0aasf",
  "estatus":1
}