POST http://localhost:3000/api/station/create
Content-Type: application/json

{
  "ID": "c9b1a6d4-7b7a-4e53-94b5-3f5dbe3a2c8a",
  "NameStation": "Estación Central",
  "Location": "Av. Libertador 1250",
  "Type": "Origen",
  "State": true
}

##########
PUT http://localhost:3000/api/station/update/c9b1a6d4-7b7a-4e53-94b5-3f5dbe3a2c8e
Content-Type: application/json

{
  "NameStation": "maipu",
  "Location": "Av. Libertador 1250",
  "Type": "Origen"

}

####
PUT  http://localhost:3000/api/station/delete/c9b1a6d4-7b7a-4e53-94b5-3f5dbe3a2c8e


##########
GET http://localhost:3000/api/station/all 

#####


POST http://localhost:3000/api/routeStation/create
Content-Type: application/json

{
  "inicio":1,
  "intermedio":[4,5,6,7,8,9],
  "final":14,
  "horaInicio":"12:00",
  "horaFin":"22:00"
}

####
GET http://localhost:3000/api/routeStation/all
###

PUT http://localhost:3000/api/routeStation/delete/1


###
GET http://localhost:3000/api/routeStation/unic/1


###
PUT http://localhost:3000/api/routeStation/update/1
Content-Type: application/json

{
  
  "final":14,
  "intermedio": [3,4,5],
  "horaInicio":"12:00",
  "horaFin":"23:00",
  "estatus":1
}

####

GET  http://perla-metro-routes-services.vercel.app/api/station/all 

####
PUT http://localhost:5128/api/route/DisabledEnabled/1

###
PUT http://localhost:5128/api/route/update/1
Content-Type:  application/json

{
  "final":14,
  "intermedio": [3,4,5],
  "horaInicio":"12:00",
  "horaFin":"23:00",
  "estatus":1
}

###
GET http://localhost:5128/api/route/unic/1

###
POST http://localhost:5128/api/route/create
Content-Type: application/json

{
  "inicio":1,
  "intermedio":[4,5,6,7,8,9],
  "final":14,
  "horaInicio":"12:00",
  "horaFin":"22:00"
}


####
put http://localhost:8080/api/Stations/ChangeStateStation/c9b1a6d4-7b7a-4e53-94b5-3f5dbe3a2c8e
