services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password123"
    volumes:
      - neo4j_data:/neo4j_data

volumes:
  neo4j_data: